# Setup
title:               Muhammed Basil
tagline:             'Software Professional'
description:         'A Technical enthusiast'
# url:                 https://beardedbatmanis.online
url:                 http://127.0.0.1:4000
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Muhammed Basil
  url:               https://twitter.com/muhammedbasilsk
  email:             muhammedbasilsk@gmail.com

# Gems
# plugins:
#   - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: GTM-WT43TH
